server:
  port: 8889

logging:
  path: logs
  file: mylog.log

spring:
  application:
    name: myAPITest
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/course
    username: root
    password: passw0rd

mybatis:
  type-aliases-package: com.course.model
  mapper-locations:
    - mapper/*